#!/bin/bash                                                                      

set -e                                                                           

touch foo                                           
